### PR TITLE
Add ROSIDL enum support

### PR DESCRIPTION
**Pull request by r7vme**
Signed-off-by: Roman Sokolkov <roman.sokolkov@apex.ai>

Main PR https://github.com/ros2/rosidl/pull/685

Related issue https://github.com/ros2/rosidl/issues/260

### CODE REVIEW

**Comment by r7vme** [comment]
@audrow could you please take a look?

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/need-reviewers-for-rosidl-related-change/26285/1

**Comment by audrow** [comment]
Here's CI to get us started: 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16960/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11524/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17358/)

**Review by audrow — COMMENTED** [review]
Looks fine to me, but let's make sure than this and the related PR don't break things downstream.

**Comment by r7vme** [comment]
@audrow thanks for review, I fixed header names in this [PR](https://github.com/ros2/rosidl/pull/685). I was able to reproduce the problem locally, seems I renamed `Enums.idl` to `EnumsMessage.idl` at some point. However, this [job](https://build.ros2.org/job/Rpr__rosidl__ubuntu_jammy_amd64/41/console) is still failing with

```
10:50:19 /tmp/ws/src/rosidl/rosidl_generator_c/test/test_interfaces.c:28:10: fatal error: rosidl_generator_c/idl/enums_message.h: No such file or directory
10:50:19    28 | #include "rosidl_generator_c/idl/enums_message.h"
10:50:19       |         
```

Locally I was able to compile successfully whole ros2 workspace with my forks.

**Comment by r7vme** [comment]
@audrow do you know may be some ROS working group , where I can present this feature and may be get some feedback?

**Comment by audrow** [comment]
> @audrow do you know may be some ROS working group , where I can present this feature and may be get some feedback?

Maybe the Middleware Working Group? @wjwwood or @clalancette, any thoughts?
https://docs.ros.org/en/rolling/The-ROS2-Project/Governance.html#working-groups-wgs

**Comment by r7vme** [comment]
Thanks @audrow.  Could you please rerun CI like you did here? https://github.com/ros2/test_interface_files/pull/20#issuecomment-1182307218

**Comment by methylDragon** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17133/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11680/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17551/)

**Comment by methylDragon** [comment]
I suspect the job failing is happening because this PR hasn't been merged yet. If CI comes up happy we can merge this and :crossed_fingers:

**Comment by r7vme** [comment]
@methylDragon thanks, we discovered issue with ROS Services support and currently working on it. I'll ping you, folks, as soon as it will be ready.

**Comment by r7vme** [comment]
Closing as I have no plans to work on this in the near time (see more details [here](https://github.com/ros2/rosidl/issues/260#issuecomment-1310490871)).

**Pull request closed without merging**
